# Generated by Django 4.2.4 on 2024-09-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_user_groups_group_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='entreprise',
            new_name='enterprise',
        ),
    ]
