# Generated by Django 4.2.4 on 2024-09-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employee_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_time',
            new_name='due_date',
        ),
    ]
